---
title: "NRES 776 Lecture 6"
subtitle: "Hypothesis test I"
author: Sunny Tseng
format:
  revealjs: 
    slide-number: true
    preview-links: auto
    #css: styles.css
    #footer: <https://quarto.org>
    theme: [default, styles.scss]
    #smaller: true
    #scrollable: true
    incremental: true
    embed-resources: true
    width: 1200
    fontsize: 1.7em
editor: visual
---

```{r setup, include = FALSE, cache=FALSE}
library(palmerpenguins)
library(tidyverse)
theme_set(theme_minimal())
```

# Happy Tuesday!

## Our schedule today

::: columns
::: {.column width="50%"}
-   Announcements (5 min)
-   Data visualization background (10 min)
-   Plot types (30 min)
-   Wrap up (5 min)
:::
:::

## Announcements

-   Discussion paper presentation

    -   15 mins for 3 presenters
    -   18 mins split room discussion
    -   2 mins wrap up

-   UNBC [Applied Analysis Hub](https://unbcaah.opened.ca/workshops/) workshop today!

-   How was your week?

### Recap

-   Sampling distribution - distribution of the sample means

-   We can use one sample to calculate mean and standard error

-   And base on these, we can get confidence interval about true mean

-   Can we generalize this process?

## Is the claim valid or not? 

A shampoo company claim that their product has 450 mm. How can we trust that? A checker 50 bottles, found the mean is about 448, standard deviation 20. Is the claim valid?

Statement 1: The volume equals 450 mm.

Statement 2: The volume is not equal to 450 mm.

95% CI is (432, 459), which covers the 450, we say that the fail to reject Result 1. The statement that "volume equals 450" is supported with confidence level 0.05!

## Hypothesis test

> A method of statistical inference used to decide whether the data at hand sufficiently support a particular hypothesis. Hypothesis testing allows us to make probabilistic statements about population parameters.

Component:

## Two hypothesis 

> Mutually exclusive statements.

::: columns
::: {.column width="50%"}
### Null Hypothesis $H_0$

###  
:::

::: {.column width="50%"}
### Alternative Hypothesis $H_a$
:::
:::

## Put questions with hypothesis

| Research question                                                       | $H_0$                                                                            | $H_a$                                                                         |
|-------------------------------------------------------------------------|----------------------------------------------------------------------------------|-------------------------------------------------------------------------------|
| Does tooth flossing affect the number of cavities?                      | Tooth flossing has **no effect** on the number of cavities.                      | Tooth flossing has **effect** on the number of cavities.                      |
| Does the amount of text highlighted in the textbook affect exam scores? | The amount of text highlighted in the textbook has **no effect** on exam scores. | The amount of text highlighted in the textbook has **effect** on exam scores. |
| Does daily meditation decrease the incidence of depression?             | Daily meditation has **no effect** on the incidence of depression.               | Daily meditation has **effect** on the incidence of depression.               |
|                                                                         |                                                                                  |                                                                               |
|                                                                         |                                                                                  |                                                                               |

## Step by step hypothesis test

## What we learned

-   We can list null hypothesis and alternative hypothesis for research questions
-   We set the confidence level that we want to test on
-   We calculate the test to support, or not support, certain hypothesis
-   Make conclusion

## Wrap up

### Before we meet again

-   Submit your first lab on Moodle
-   Read discussion paper, can be found on discussion paper rubric

### Next time

-   Thur. 8am lab, virtual on zoom
-   With your morning coffee/tea and relaxed mood
-   It's our final virtual lab in September!
