---
title: "NRES 776 Lab 1"
subtitle: "Introduction to R"
author: Sunny Tseng
format:
  revealjs: 
    slide-number: true
    preview-links: auto
    css: styles.css
    #footer: <https://quarto.org>
    theme: [default, styles.scss]
    smaller: true
    scrollable: true
    incremental: true
    embed-resources: true
editor: visual
---

# Welcome to your first R lab!

## Our schedule today

-   Discussion paper presentation (30 min)

-   Lab intro (10 min)

-   Intro to R, R studio, and gentle intro to programming (60 min)

-   Quiet time for practice (60 min)

## About these labs

### Format

-   

### R is hard: But we are here together!

-   Don't expect to remember everything (language learning)

-   Be expose to the language

## ImpostR Syndrome

## Why R?

R is hard - but powerful, beautiful, reproducible, and free

-   A lot of observations

-   I used R Quarto to make the slides

## What is R?

## What is R Studio?

-   R Studio is not R, RStudio is a Graphic User Interfaces (GUI)

-   You can only use R console to program, but RStudio makes your life easier

-   Think it as a


## Let's get started with RStudio!

## Your first R code!

## Wrap up

### Before we meet again

-   

### Next time

-   Next Tue. lecture, Virtual on zoom, with Sunny
